--- 
pool: 
  demands: 
    - npm
  vmImage: ubuntu-16.04
steps: 
  - 
    displayName: "Use .NET Core SDK 3.1.100"
    inputs: 
      packageType: sdk
      version: "3.1.100"
    task: UseDotNet@2
  - 
    displayName: "Run npm install"
    inputs: 
      verbose: false
    task: Npm@1
  - 
    displayName: "Compile Sass assets"
    script: "./node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot"
  - 
    displayName: "Run gulp tasks"
    task: gulp@1
  - 
    displayName: "Write build info"
    script: "echo \"$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)\" > buildinfo.txt"
    workingDirectory: Tailspin.SpaceGame.Web/wwwroot
  - 
    displayName: "Restore project dependencies"
    inputs: 
      command: restore
      projects: "**/*.csproj"
    task: DotNetCoreCLI@2
  - 
    displayName: "Build the project - Release"
    inputs: 
      arguments: "--no-restore --configuration Release"
      command: build
      projects: "**/*.csproj"
    task: DotNetCoreCLI@2
trigger: 
  - "*"
variables: 
  buildConfiguration: Release
